# Generated by Django 2.1.7 on 2020-02-13 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='abstract',
        ),
        migrations.DeleteModel(
            name='architechture',
        ),
        migrations.DeleteModel(
            name='bird',
        ),
        migrations.DeleteModel(
            name='exif',
        ),
        migrations.DeleteModel(
            name='landscape',
        ),
        migrations.DeleteModel(
            name='lifestyle',
        ),
        migrations.DeleteModel(
            name='long_exposure',
        ),
        migrations.DeleteModel(
            name='night_life',
        ),
        migrations.DeleteModel(
            name='portraiture',
        ),
        migrations.DeleteModel(
            name='street',
        ),
        migrations.DeleteModel(
            name='vogue',
        ),
        migrations.AddField(
            model_name='wildlife',
            name='aperture',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='wildlife',
            name='brand',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='wildlife',
            name='date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='wildlife',
            name='focallength',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='wildlife',
            name='iso',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='wildlife',
            name='lens',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='wildlife',
            name='model',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='wildlife',
            name='shutterspeed',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='board',
            name='detail1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='display.wildlife'),
        ),
        migrations.AddField(
            model_name='board',
            name='detail10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='display.wildlife'),
        ),
        migrations.AddField(
            model_name='board',
            name='detail2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='display.wildlife'),
        ),
        migrations.AddField(
            model_name='board',
            name='detail3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='display.wildlife'),
        ),
        migrations.AddField(
            model_name='board',
            name='detail4',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='display.wildlife'),
        ),
        migrations.AddField(
            model_name='board',
            name='detail5',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='display.wildlife'),
        ),
        migrations.AddField(
            model_name='board',
            name='detail6',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='display.wildlife'),
        ),
        migrations.AddField(
            model_name='board',
            name='detail7',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='display.wildlife'),
        ),
        migrations.AddField(
            model_name='board',
            name='detail8',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='display.wildlife'),
        ),
        migrations.AddField(
            model_name='board',
            name='detail9',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='display.wildlife'),
        ),
    ]
