# Generated by Django 2.1.7 on 2020-02-20 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0002_auto_20200213_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photographer', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='images/images')),
                ('description', models.CharField(max_length=150)),
                ('brand', models.CharField(blank=True, max_length=50, null=True)),
                ('model', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.CharField(blank=True, max_length=50, null=True)),
                ('shutterspeed', models.CharField(blank=True, max_length=50, null=True)),
                ('focallength', models.CharField(blank=True, max_length=50, null=True)),
                ('aperture', models.CharField(blank=True, max_length=50, null=True)),
                ('iso', models.CharField(blank=True, max_length=50, null=True)),
                ('lens', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='board',
            name='detail1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='display.images'),
        ),
        migrations.AlterField(
            model_name='board',
            name='detail10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='display.images'),
        ),
        migrations.AlterField(
            model_name='board',
            name='detail2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='display.images'),
        ),
        migrations.AlterField(
            model_name='board',
            name='detail3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='display.images'),
        ),
        migrations.AlterField(
            model_name='board',
            name='detail4',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='display.images'),
        ),
        migrations.AlterField(
            model_name='board',
            name='detail5',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='display.images'),
        ),
        migrations.AlterField(
            model_name='board',
            name='detail6',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='display.images'),
        ),
        migrations.AlterField(
            model_name='board',
            name='detail7',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='display.images'),
        ),
        migrations.AlterField(
            model_name='board',
            name='detail8',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='display.images'),
        ),
        migrations.AlterField(
            model_name='board',
            name='detail9',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='display.images'),
        ),
        migrations.DeleteModel(
            name='wildlife',
        ),
    ]
