# Generated by Django 2.1.7 on 2020-02-20 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0003_auto_20200221_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='detail10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='display.images'),
        ),
        migrations.AlterField(
            model_name='board',
            name='detail2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='display.images'),
        ),
        migrations.AlterField(
            model_name='board',
            name='detail3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='display.images'),
        ),
        migrations.AlterField(
            model_name='board',
            name='detail4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='display.images'),
        ),
        migrations.AlterField(
            model_name='board',
            name='detail5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='display.images'),
        ),
        migrations.AlterField(
            model_name='board',
            name='detail6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='display.images'),
        ),
        migrations.AlterField(
            model_name='board',
            name='detail7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='display.images'),
        ),
        migrations.AlterField(
            model_name='board',
            name='detail8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='display.images'),
        ),
        migrations.AlterField(
            model_name='board',
            name='detail9',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='display.images'),
        ),
    ]
